server:
    port: '${PORT:8080}'
spring:
    application:
        name: entrega-app

logging:
    level:
        com.amazonaws.services.dynamodbv2.datamodeling: DEBUG
        com.entrega: DEBUG

amazon:
    aws:
        accesskey: ${AWS_ACCESS_KEY}
        secretkey: ${AWS_SECRET_KEY}
    dynamodb:
        endpoint: ${AWS_END_POINT}
        # Se estiver usando DynamoDB local, descomente a linha abaixo e comente a linha acima
        # endpoint: ${AWS_END_POINT_LOCAL}
        region: ${AWS_REGION}

springdoc:
    info:
        title: Microsserviço de Entrega
        description: API para gerenciamento de entregas
        version: 1.0.0
    paths-to-match:
        - /api/**
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs
        enabled: true
