package com.entrega.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "db_entrega")
public class Entrega {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private Long id;

    @DynamoDBAttribute(attributeName = "remetente")
    private String remetente;

    @DynamoDBAttribute(attributeName = "destinatario")
    private String destinatario;

    @DynamoDBAttribute(attributeName = "enderecoEntrega")
    private String enderecoEntrega;

    @DynamoDBAttribute(attributeName = "status")
    private String status;

}