package com.entrega.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.entrega.util.StringListConverter;
import lombok.Data;
import org.springframework.data.annotation.Id;

import java.util.List;


@DynamoDBTable(tableName = "db_entrega")
@Data
public class Entrega {

    private String id;
    private Cliente cliente;
    private String dataPedido;
    private double totalPedido;
    private String formaPagamento;
    private List<PedidoProduto> pedidoProdutos;
    private String status;
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "cliente")
    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    @DynamoDBAttribute(attributeName = "dataPedido")
    public String getDataPedido() {
        return dataPedido;
    }

    public void setDataPedido(String dataPedido) {
        this.dataPedido = dataPedido;
    }
    @DynamoDBAttribute(attributeName = "totalPedido")
    public double getTotalPedido() {
        return totalPedido;
    }

    public void setTotalPedido(double totalPedido) {
        this.totalPedido = totalPedido;
    }
    @DynamoDBAttribute(attributeName = "formaPagamento")
    public String getFormaPagamento() {
        return formaPagamento;
    }

    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }
    @DynamoDBAttribute(attributeName = "pedidoProdutos")
    public List<PedidoProduto> getPedidoProdutos() {
        return pedidoProdutos;
    }

    public void setPedidoProdutos(List<PedidoProduto> pedidoProdutos) {
        this.pedidoProdutos = pedidoProdutos;
    }
    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}